
# Site settings
title: OneSlashTooFar
email: outsajder@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  pnowy home page
url: "http://pnowy.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
environment: prod

github_username:  pnowy
stackoverflow_profile: http://stackoverflow.com/users/328121/przemek
linkedin_profile: https://www.linkedin.com/in/przemeknowak

kramdown:
   input: GFM

exclude:
  - "README.md"
  - "devbuild.bat"
  - "devserve.bat"
