
# Site settings
title: OneSlashTooFar
email: outsajder@outlook.com
description: > # this means to ignore newlines until "baseurl:"
  pnowy home page
url: "http://pnowy.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog
JEKYLL_ENV: production

github_username:  pnowy
stackoverflow_profile: http://stackoverflow.com/users/328121/przemek
linkedin_profile: https://www.linkedin.com/in/przemeknowak

kramdown:
   input: GFM
   syntax_highlighter_opts:
       css_class: 'highlight'
       line_numbers: true # bad idea, spans don't need linenos and would inherit this option
       span:
         line_numbers: false
       block:
         line_numbers: true
         start_line: 1

exclude:
  - "README.md"
  - "serve.sh"
  - "build.sh"

gems:
  - jekyll-seo-tag
  - jekyll-sitemap